config/routes.rb
Rails.application.routes.draw do
  
  root "pages#home"
  
  get '/about', to: "pages#about"
  
  get '/help', to: 'pages#help'
  
  
  resources :todos
  resources :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :todos
  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/pages_controller.rb
class PagesController < ActionController::Base
  def home
    
  end
  
  def about
    
  end
  
  def help
    
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:edit, :show, :update, :destroy]
  
  
  def new
    @todo = Todo.new
  end
   
  def edit
    
  end
  
  def create 
    @todo = Todo.create(todo_params)
    
    if @todo.save
      flash[:notice] = "Todo was successfully created"
      redirect_to todo_path(@todo)
    else
      render 'new'
    end
  end
  
  def index
    @todos = Todo.all
  end
  
  def destroy
      @todo.destroy
      flash[:notice] = "Todo was successfully deleted." 
      redirect_to todos_path
  end
    
  def show
     
  end
 
  def update
    if @todo.update!(todo_params)
      flash[:notice] = "Todo was successfully updated"
      redirect_to @todo
    else
      render 'edit'
    end
  end
  
  private

  def set_todo
    @todo = Todo.find(params[:id])
  end
  
  def todo_params
    params.require(:todo).permit(:name, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @users = User.all
  end
  
  def new 
    @user = User.new
  end
  
  def create
    @user = User.create(user_params)
    
    if @user.save
      flash[:notice] = "You have successfully signed up"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end 
  
  def show
    
  end
  
  def edit
    
  end
  
  def update
    if @user.update!(user_params)
      flash[:notice] = "User was successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    @user.destroy
      flash[:notice] = "User was successfully deleted." 
      redirect_to users_path
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h2>About Us</h2>

<p>We are learning to create web application using Ruby on Rails. <br/> Man, does she run along the tracks.</p>

app/views/pages/help.html.erb
<h1>S . O . S</h1>

<h2>I am crying out for help!</h2>

app/views/pages/home.html.erb
<h1>Things To Do App</h1>

<p>Make an list of your todos, share, edit, and delete those that all really done</p>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>
  <div class="errors">
    <h2 >The following errors prevented the todo from being saved</h2>
    <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<div class="form">
  
<%= form_for @todo do |f| %>
  
  <p>
  <%= f.label :name %> <br/>
  <%= f.text_field :name %> 
  </p>
  
  <p>
  <%= f.label :description %> <br/>
  <%= f.text_area :description %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>

<% end %>

</div>

<%= link_to 'Back to listing', todos_path, class: "button" %>

app/views/todos/edit.html.erb
<div class="container">
  
  <div class="header">
    <h1>Editing Todo</h1>
  </div>
  
  <hr>
  
  <%= render 'form' %>
  
</div>

app/views/todos/index.html.erb
<div class="container">
  <div class="header">
    <h1>List of todos</h1>
  </div>
  <hr>
  <div class="link">
    <%= link_to "Create a todo", new_todo_path, class: "button" %>
  </div>  
  <table>
    <tr class:"tab-row" >
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
   
    <% @todos.each do |todo| %>
      <tr class:"tab-row">
        <td><%= todo.name %></td>
        <td><%= todo.description %></td>
        <td><%= link_to 'Show', todo_path(todo), class: "manage-todo" %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo), class: "manage-todo" %></td>
        <td><%= link_to 'Delete', todo_path(todo),
                method: :delete,
                data: { confirm: 'Are you sure?' }, class: "manage-todo" %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/todos/new.html.erb
<div class="container">

  <div class="header">
    <h1>Create a new todo</h1>
  </div>
  
  <hr>
  
  <%= render 'todos/form' %>
  

</div>

app/views/todos/show.html.erb
<div class="container">
  <div class="header">
    <h1>Showing a todo</h1>
  </div>
  
  <hr>
  
  <div class="main">
    <p>
      <strong>Name:</strong>
      <%= @todo.name %>
    </p>
     
     <hr>
     
    <p>
      <strong>Description:</strong>
      <%= @todo.description %>
    </p>
  </div>
  
  <div class="link">
    <%= link_to 'Edit todo', edit_todo_path(@todo), class: "manage-todo" %> |
    <%= link_to "Back to listing", todos_path , class: "manage-todo"%>
  </div>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div class="errors">
    <h2 >The following errors prevented the user from being saved</h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<div class="form">
  
<%= form_for @user do |f| %>
  
  <p>
  <%= f.label :name %> <br/>
  <%= f.text_field :name, placeholder: "enter your name" %> 
  </p>
  
  <p>
  <%= f.label :email %> <br/>
  <%= f.text_field :email, placeholder: "enter your email address" %>
  </p>
  
  
  <p>
    <%= f.submit %>
  </p>

<% end %>

</div>

<%= link_to 'Back to user listing', users_path, class: "button" %>

app/views/users/edit.html.erb
<div class="container">

  <div class="header">
    <h1>Edit your information</h1>
  </div>
  
  <hr>


  <%= render 'form' %>

app/views/users/index.html.erb
<div class="container">
  <div class="header">
    <h1>List of Users</h1>
  </div>
  <hr>
  
  <div class="link">
    <%= link_to "Sign Up", new_user_path, class: "button" %>
  </div>

  <table>
      <tr class:"tab-row" >
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    <% @users.each do |user| %>
      <tr>
      <td><%= user.name %></li></td>
      <td><%= link_to 'Show', user_path(user), class: "manage-todo" %></td>
      <td><%= link_to 'Edit', edit_user_path(user), class: "manage-todo" %></td>
      <td><%= link_to 'Delete', user_path(user),
                  method: :delete,
                  data: { confirm: 'Are you sure?' }, class: "manage-todo" %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/new.html.erb
<div class="container">

  <div class="header">
    <h1>New user? Sign up</h1>
  </div>
  
  <hr>


  <%= render 'form' %>

app/views/users/show.html.erb
<div class="container">
  <div class="header">
    <h1><%= @user.name.capitalize %>'s Profile</h1>
  </div>
  
  <hr>
  
  <div class="main">
    <p>
      <strong>Name:</strong>
      <%= @user.name.capitalize %>
    </p>
  </div>
  
  <div class="link">
    <%= link_to 'Edit user', edit_user_path(@user), class: "manage-todo" %> |
    <%= link_to "Back to user listing", users_path , class: "manage-todo"%>
  </div>
</div>